### PR TITLE
Add HTMLSlotElement.

### PR DESCRIPTION
**Pull request by kaycebasques**

### CODE REVIEW

**Comment by jpmedley** [comment]
Kayce,

You've got lesson 1 down, meaning what you've done so far looks good. Here's lesson 2. Here's an example I'll refer to: https://github.com/google/Chrome.Docs/blob/master/m47/InputDeviceCapabilities.md
- Go ahead and create a page for the Shadow DOM API. You don't need to write it, but at least give it a title. THEN link to it from the words 'Shadow DOM API'. 
- Does this interface have a constructor? If so add it above the Properties.
- Qualify the properties and methods. For example HTMLSlotElement.name. (It's an MDN thing.)
- Put parens at the end of method names.

Also, is there any wisdom you can add to the bare description. I didn't see much in the spec, but if you know anything...

**Comment by jpmedley** [comment]
Ping!

**Comment by jpmedley** [comment]
Kayce,

Can you please jump on this?

**Comment by kaycebasques** [comment]
I'll work on it today.

**Comment by kaycebasques** [comment]
@jpmedley I'll work on it today

**Comment by jpmedley** [comment]
Thank you.

Joe Medley | Technical Writer, DevPlat | jmedley@google.com | 816-678-7195

**Comment by kaycebasques** [comment]
ok @jpmedley take a look

**Comment by jpmedley** [comment]
Kayce,

Thanks for doing this. Everything looks good.

I'm going to merge, this but I'm going to send you a new PR in a few
minutes. There are a few things to tweak still, but they're minor and
they're things I should've provided in instructions. Please look it over
when you get it.

Joe

Joe Medley | Technical Writer, DevPlat | jmedley@google.com | 816-678-7195

**Pull request merged**
